#!/usr/bin/perl

#
# os-identifier - Generate identifier for the Config5 OS system property
#
# $Id: os-identifier 190 2013-03-18 08:47:37Z walteste $
# $HeadURL: https://svn.isg.inf.ethz.ch/svn/isg/config5/trunk/examples/utils/os-identifier $
#

use strict;
use warnings;

sub slurp($);

my $os = 'Unknown-OS';

if ($^O eq 'linux')
{
   $os = 'Linux';

   # Red Hat Enterprise Linux and Fedora
   if (-f '/etc/redhat-release')
   {
      my ($line) = slurp '/etc/redhat-release';

      $os = "RHEL-$1-$2"
         if $line =~ /^Red Hat Enterprise Linux (\S+) release (\d+)(?:\.\d+).* \(.*\)$/;
      $os = "Fedora-$1"
         if $line =~ /^Fedora release (\d+) \(.*\)$/;
   }
}

print "$os\n";

sub slurp($)
{
   open my $fh, "<$_[0]" or die "** Failed to read '$_[0]': $!";
   my @data = (<$fh>);
   chomp @data;
   @data;
}

